const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Booking
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',

  // Field
  FIELD_NOT_ACTIVE: 'FIELD_NOT_ACTIVE',
  SUBFIELD_NOT_FOUND: 'SUBFIELD_NOT_FOUND',
  FIELD_NOT_VERIFIED: 'FIELD_NOT_VERIFIED',
  PROMO_CODE_INVALID: 'PROMO_CODE_INVALID',
  DUPLICATE_PROMO_CODE: 'DUPLICATE_PROMO_CODE',
  PRICE_OVERRIDE_NOT_FOUND: 'PRICE_OVERRIDE_NOT_FOUND',
  PROMOTION_NOT_FOUND: 'PROMOTION_NOT_FOUND',

  // Billing
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
  SUBSCRIPTION_PAST_DUE: 'SUBSCRIPTION_PAST_DUE',
  INVOICE_NOT_PAYABLE: 'INVOICE_NOT_PAYABLE',

  // Server
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = ErrorCode;
